### ISSUE TITLE
书里的版权页的最后年份没更新

### ISSUE THREAD

**Issue by GasinAn** [huangxg/lnotes#13]
`lnotes/src/copyright.tex`

包老师可以在仓库里加一个新版本发布笔记文件，名字可以取成`new_version.txt`之类的，然后把新版本发布步骤写里头，每次新版本发布都照着做来避免自己忘了什么。

注：我的名字已经在致谢里了。

**Comment by huangxg** [comment]
谢谢

**Comment by Freed-Wu** [comment]
可以考虑每次发布新版本往 CTAN 上发布一个。

CTAN 上也有一些 (La)TeX 中文教程：

- https://ctan.org/pkg/impatient
- https://ctan.org/pkg/lshort-zh-cn
