### ISSUE TITLE
请教一个不太重要的关于内容的问题：狭义的印刷是否等于压印？

### ISSUE THREAD

**Issue by gingerkitti** [huangxg/lnotes#7]
在lnotes2.pdf的173页中有提到

> 一般而言，印刷 (printing) 包含四种要素：印版 (image carrier) 、印刷材料、墨、印刷设备；以及两大过程：排版 (typesetting) 和压印 (presswork)。排版负责转换原始的图像和文字，在印版上制作印纹；而压印则负责给印纹上墨，在印刷材料上印制出图文。**有时人们会把压印和印刷这两个词混用，我们姑且认为广义的印刷包括排版和狭义的印刷。**

是否可以理解为狭义的印刷等于压印？

**Comment by huangxg** [comment]
旧时候是这样，但是现在有喷墨和激光打印等，我不太确定这些新技术算不算压印。

**Comment by gingerkitti** [comment]
非常感谢您的解答
